# Run with python main.py configs/gsm_cot.yaml

wandb_project: coconut-reconstruction
run_name: gsm-coconut-single

only_eval: False
debug: False
single_sample: True
single_sample_index: 2
single_sample_steps_per_epoch: 100
bf16: True

cot: False
coconut: True

c_thought: 1
epochs_per_stage: 1
max_latent_stage: 6
pad_latent_to_max: True
save_only_improve: False

num_epochs: 10
lr: !!float "1e-4"
weight_decay: 0.01
batch_size_training: 16
gradient_accumulation_steps: 2

model_id: Qwen/Qwen3-0.6B
save_path: checkpoints
load_model_path: checkpoints/gsm-cot/260614_003154/checkpoint_3.pt
resume_from_epoch: 0

dataset_name: openai/gsm8k
dataset_config_name: main
train_split: train
val_split: test
max_new_tokens: 64

step_extraction_method: equations         # equations extract everything between << and >>. cot extractes only the cot.
# step_extraction_method: cot
add_special_tokens: True

reset_optimizer: False
seed: 42
uniform_prob: 0.0
